services:
  sqlserver: # Nombre del servicio
    image: mcr.microsoft.com/mssql/server:2022-latest # Imagen de Docker para SQL Server 2022
    container_name: sqlserver # Nombre del contenedor
    env_file: .env # Archivo con variables de entorno
    ports:
      - 1433:1433 # Mapea el puerto 1433 del contenedor al puerto 1433 del host
    volumes:
      - ./backups:/var/opt/mssql/backups # Carpeta local para archivos .bak
      - ./sqlserver_data:/var/opt/mssql/data # Volumen persistente para los datos de la base de datos

#bash connection(not encrypted)
# /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P yourStrong#Pass -No
